### ISSUE TITLE
Build fails with rx java class not found

### ISSUE THREAD

**Issue by vincent-paing** [SiimKinks/sqlitemagic#9]
I can't seem to run the app because the generated class imported classes from rxjava. Even after adding the rxjava to my gradle compilation, it still fails to run. I think the rxajva implementation should be able to opt-in instead of just forcing it.

**Comment by SiimKinks** [comment]
For me it works with added RxJava dependency. Try to sync, clean and rebuild your project.
Currently, since one of the the main goals of this library was to provide reactive semantics on database access, there hasn't been any motivation to provide opt-out possibilities.
This may be a goal for version 1.0.0 though… (see #6)
